# Blog info
blog_name: 东隅已逝丶
slogan: 三年二班小十七同学
url: https://dongyuyishi.github.io/

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: 前端,设计,Hexo主题,前端开发,博客,design,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  # - name: Project
  #   url: /project/
  #   target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/dongyuyishi
    target_blank: true
  - name: Weibo
    url: https://weibo.com/3762529591
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: true # 不在新页面打开
  # - name: 分类
  #   url: /category/
  #   target_blank: true
  - name: 标签
    url: /tag/
    target_blank: true
  - name: 搜索
    url: /search/
    target_blank: true # 在新页面打开
  # - name: 友链
  #   url: /link/
  #   target_blank: true
  - name: 关于
    url: /about/
    target_blank: true
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开


page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 导航

search_slogan:
  isShow: true # true|fase
  text: Can you find me in the world ~

# link_slogan:
#   isShow: true # true|fase
#   text: 交换友链可以邮件 zhao1046222061@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 感谢大侠支持本弟弟~
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/wechat_code.jpg
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/alipay_code.jpg




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics: UA-131891371-1
#baidu_analytics: d699d7cf07bd14afb8c02c436f6fec61

# Comment service

# disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: true # 如果使用 gitalk，请设置改之为true
  clientID: 40fe06f3e6b774d4a39d
  clientSecret: f44f3da134dd4cb804063a6db731fa1f556cda19
  repo: dongyuyishi.github.io
  owner: dongyuyishi
  admin: dongyuyishi
  # id: window.location.pathname


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# Online contact 
daovoice: true
daovoice_app_id: 68f066ed


# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "姓名：小十七"
    - "性别：男"
    - "生日：1998.06.12"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@dongyuyishi"
    text_value_url: https://github.com/dongyuyishi
  - type: weibo
    icon: icon-weibo
    text_key: Weibo
    text_value: "@三年二班小十七同学"
    text_value_url: https://weibo.com/3762529591
  - type: Bilibili
    icon: icon-Bilibili
    text_key: Bilibili
    text_value: "@东隅已逝丶_"
    text_value_url: http://space.bilibili.com/79916930?
  - type: Douban
    icon: icon-Douban
    text_key: Douban
    text_value: "东隅已逝丶"
    text_value_url: https://www.douban.com/people/157228082/
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "zhao1046222061@gmail.com"
  - type: location
    icon: icon-location
    text_value: 石家庄河东科技幼儿园

# link:
#   - name: 织网
#     info: 身体和灵魂，总有一个在路上
#     url: http://zheng-ji.info/
#     avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
#   - name: Dongyado
#     info: 生命不止，折腾不息
#     url: http://dongyado.com/
#     avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
#   - name: OrangeCoder
#     info: android ffmpeg nodejs gradle
#     url: http://orangecoder.com/
#     avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
#   - name: EverET
#     info: 好记性不如烂笔头
#     url: http://everet.org/about-me/
#     avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
#   - name: 题叶
#     info: FP, GUI, Writing
#     url: http://tiye.me/
#     avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
#   - name: McChen
#     info: Stay Hungry, Stay Foolish
#     url: http://mcchen.club/
#     avatar: https://avatars0.githubusercontent.com/u/8033333?v=3&s=100


# project:
#   - type: personal
#     name: fexo
#     url: https://github.com/forsigner/fexo
#     intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  # - type: personal
  #   name: beside
  #   url: https://github.com/forsigner/beside
  #   intro: I need you beside me
  # - type: personal
  #   name: web-fontmin
  #   url: https://github.com/forsigner/web-fontmin
  #   intro: 字体子集化，在线提取你需要的字体
  # - type: personal
  #   name: magic-check
  #   url: https://github.com/forsigner/magic-check
  #   intro: Beautify Radio and Checkbox with pure CSS
  # - type: personal
  #   name: nice-bar
  #   url: https://github.com/forsigner/nice-bar
  #   intro: A nice and lightweight scrollbar
  # - type: personal
  #   name: angular-nice-bar
  #   url: https://github.com/forsigner/angular-nice-bar
  #   intro: A nice and lightweight scrollbar in Angular
  # - type: personal
  #   name: fo-popover
  #   url: https://github.com/forsigner/fo-popover
  #   intro: A nice popover for Angular
  # - type: personal
  #   name: fo-tooltip
  #   url: A nice tooltip for Angular
  #   intro: https://github.com/forsigner/fo-tooltip
  # - type: personal
  #   name: fo-modal
  #   url: https://github.com/forsigner/fo-modal
  #   intro: A nice modal for Angular
  # - type: personal
  #   name: mocer
  #   url: https://github.com/forsigner/mocer
  #   intro: Setup a mock server easily
  # - type: personal
  #   name: node-pngdefry
  #   url: https://github.com/forsigner/node-pngdefry
  #   intro: Repairing iPhone fried PNGs using Node.js
  # - type: personal
  #   name: ng-simditor
  #   url: https://github.com/forsigner/ng-simditor
  #   intro: Angular directive for simditor